//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDC_LICENSE                     3
#define IDD_MAIN                        100
#define IDD_GLOBAL                      101
#define IDD_QUANT                       102
#define IDD_2PASS                       103
#define IDD_RC_2PASS2                   104
#define IDD_CREDITS                     105
#define IDD_CPU                         106
#define IDD_ENC                         107
#define IDD_QUANTMATRIX                 108
#define IDD_ABOUT                       109
#define IDD_2PASSALT                    110
#define IDD_RC_2PASS2_ALT               111
#define IDD_POSTPROC                    112
#define IDD_RC_CBR                      113
#define IDD_PROFILE                     114
#define IDD_RC_2PASS1                   116
#define IDD_MOTION                      117
#define IDD_TOOLS                       120
#define IDD_ZONE                        121
#define IDD_LEVEL                       122
#define IDD_DEC                         124
#define IDD_STATUS                      125
#define IDD_AR                          126
#define IDD_BITRATE                     127
#define IDD_LICENSE                     129
#define IDR_GPL                         131
#define IDD_COMMON                      132
#define WIZ_CYDLG                       140
#define PROP_MIN_CYDLG                  144
#define PROP_SM_CYDLG                   188
#define PROP_MIN_CXDLG                  212
#define PROP_MED_CYDLG                  215
#define PROP_LG_CYDLG                   218
#define PROP_MED_CXDLG                  227
#define PROP_LG_CXDLG                   252
#define WIZ_CXDLG                       276
#define IDC_MODE                        1000
#define IDC_SLIDER                      1001
#define IDC_QUALITY                     1002
#define IDC_QUALITY_ADV                 1005
#define IDC_OTHER                       1006
#define IDC_DEFAULTS                    1007
#define IDC_PROFILE                     1008
#define IDC_MOTION                      1009
#define IDC_QUANTTYPE                   1010
#define IDC_FOURCC                      1011
#define IDC_MAXKEY                      1012
#define IDC_LUMMASK                     1013
#define IDC_MINIQUANT                   1014
#define IDC_MAXIQUANT                   1015
#define IDC_MAXPQUANT                   1017
#define IDC_MINBQUANT                   1018
#define IDC_MAXBQUANT                   1019
#define IDC_QUANTMATRIX                 1020
#define IDC_KFBOOST                     1021
#define IDC_MINKEY                      1022
#define IDC_DISCARD1PASS                1023
#define IDC_DUMMY2PASS                  1024
#define IDC_CURVECOMPH                  1025
#define IDC_CURVECOMPL                  1026
#define IDC_PAYBACK                     1027
#define IDC_PAYBACKBIAS                 1028
#define IDC_PAYBACKPROP                 1029
#define IDC_STATS1                      1030
#define IDC_STATS2                      1031
#define IDC_CREDITS_START               1034
#define IDC_CREDITS_START_BEGIN         1035
#define IDC_CREDITS_START_END           1036
#define IDC_CREDITS_END                 1037
#define IDC_CREDITS_END_START           1038
#define IDC_CREDITS_END_BEGIN           1039
#define IDC_CREDITS_END_END             1040
#define IDC_CREDITS_RATE_RADIO          1041
#define IDC_CREDITS_RATE                1042
#define IDC_CREDITS_QUANT_RADIO         1043
#define IDC_CREDITS_QUANTI              1044
#define IDC_CREDITS_QUANT_STATIC        1045
#define IDC_CREDITS_QUANTP              1046
#define IDC_CREDITS_SIZE_RADIO          1047
#define IDC_CREDITS_START_SIZE          1048
#define IDC_CREDITS_END_STATIC          1049
#define IDC_CREDITS_END_SIZE            1050
#define IDC_CPU_AUTO                    1051
#define IDC_CPU_FORCE                   1052
#define IDC_CPU_MMX                     1053
#define IDC_CPU_MMXEXT                  1054
#define IDC_CPU_SSE                     1055
#define IDC_CPU_SSE2                    1056
#define IDC_CPU_3DNOW                   1057
#define IDC_CPU_3DNOWEXT                1058
#define IDC_LOAD                        1059
#define IDC_CPU_SSE3                    1059
#define IDC_SAVE                        1060
#define IDC_CPU_SSE4                    1060
#define IDC_WEBSITE                     1061
#define IDC_BUILD                       1062
#define IDC_CORE                        1063
#define IDC_USEALT                      1193
#define IDC_USEAUTO                     1194
#define IDC_USEAUTOBONUS                1196
#define IDC_CURVETYPE                   1198
#define IDC_INTERLACING                 1203
#define IDC_MAXBFRAMES                  1205
#define IDC_HINTFILE                    1206
#define IDC_HINT_BROWSE                 1208
#define IDC_HINTEDME                    1209
#define IDC_OVERIMP                     1210
#define IDC_MAXBITRATE                  1211
#define IDC_CBR_REACTIONDELAY           1212
#define IDC_CBR_AVERAGINGPERIOD         1213
#define IDC_CBR_BUFFER                  1214
#define IDC_PACKED                      1215
#define IDC_MAXBFRAMES_S                1217
#define IDC_DX50BVOP                    1219
#define IDC_DEBUG                       1220
#define IDC_NUMTHREADS                  1221
#define IDC_NUMTHREADS_STATIC           1223
#define IDC_FRAMEDROP                   1224
#define IDC_FRAMEDROP_STATIC            1225
#define IDC_KFTRESHOLD                  1226
#define IDC_KFREDUCTION                 1227
#define IDC_GREYSCALE                   1228
#define IDC_CREDITS_GREYSCALE           1229
#define IDC_SPECIAL_BUILD               1230
#define IDC_GMC                         1231
#define IDC_CHROMAME                    1233
#define IDC_DEBLOCK_Y                   1235
#define IDC_DEBLOCK_UV                  1236
#define IDC_REDUCED                     1237
#define IDC_VHQ                         1238
#define IDC_CHROMA_OPT                  1239
#define IDC_STATS                       1240
#define IDC_MODE_ADV                    1241
#define IDC_PROFILE_ADV                 1242
#define IDC_ADD                         1243
#define IDC_REMOVE                      1245
#define IDC_EDIT                        1246
#define IDC_PROFILE_BITRATE             1256
#define IDC_PROFILE_PROFILE             1258
#define IDC_BVOP                        1261
#define IDC_CLOSEDGOV                   1266
#define IDC_QUANTTYPE_S                 1290
#define IDC_LEVEL_PROFILE               1293
#define IDC_LEVEL_WIDTH                 1294
#define IDC_LEVEL_HEIGHT                1295
#define IDC_LEVEL_FPS                   1296
#define IDC_LEVEL_VMV                   1297
#define IDC_LEVEL_VCV                   1298
#define IDC_LEVEL_VBV                   1299
#define IDC_LEVEL_BITRATE               1300
#define IDC_BITRATE                     1302
#define IDC_BITRATE_MIN                 1303
#define IDC_BITRATE_MAX                 1304
#define IDC_TRELLISQUANT                1306
#define IDC_BITRATE_S                   1307
#define IDC_VOPDEBUG                    1308
#define IDC_DISPLAY_STATUS              1335
#define IDC_FULL1PASS                   1338
#define IDC_DEC_DY                      1339
#define IDC_OVERFLOW_CONTROL_STRENGTH   1349
#define IDC_PAR                         1354
#define IDC_PARX                        1355
#define IDC_PARY                        1356
#define IDC_TURBO                       1369
#define IDC_DEC_DUV                     1370
#define IDC_DEC_DR                      1371
#define IDC_DEC_DRY                     1371
#define IDC_DEBUGOUTPUT                 1372
#define IDC_DEC_DRUV                    1372
#define IDC_SHOWINTERNALS               1373
#define IDC_DEC_FE                      1374
#define IDC_BITRATE_HOURS               1380
#define IDC_BITRATE_FPS                 1383
#define IDC_BITRATE_ADV                 1392
#define IDC_DEC_BRIGHTNESS              1393
#define IDC_TFF                         1394
#define IDC_VHQ_BFRAME                  1395
#define IDC_LICENSE_TEXT                1396
#define IDC_LEVEL_PEAKRATE_S            1397
#define IDC_LEVEL_PEAKRATE_DEV          1397
#define IDC_LEVEL_BITRATE_S             1398
#define IDC_LEVEL_VBV_S                 1399
#define IDC_LEVEL_STREAM_S              1399
#define IDC_LEVEL_VBV_G                 1400
#define IDC_LEVEL_DIM_S                 1401
#define IDC_LEVEL_VMV_S                 1402
#define IDC_LEVEL_VCV_S                 1403
#define IDC_LEVEL_LEVEL_G               1404
#define IDC_LEVEL_STREAM                1406
#define IDC_LEVEL_PEAKRATE              1407
#define IDC_LEVEL_AVGRATE_DEV           1408

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1408
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
